# Generated by Django 3.2 on 2021-06-23 23:26

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('name', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('color', colorfield.fields.ColorField(default='#FFFFFF', max_length=18)),
                ('resistant_to', models.ManyToManyField(related_name='_pokedex_type_resistant_to_+', to='pokedex.Type')),
                ('weak_to', models.ManyToManyField(related_name='_pokedex_type_weak_to_+', to='pokedex.Type')),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('pokedex_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.FilePathField(path='/img')),
                ('poke_type', models.ManyToManyField(to='pokedex.Type')),
            ],
        ),
    ]
