# Generated by Django 3.2 on 2021-06-24 22:15

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('name', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('color', colorfield.fields.ColorField(default='#FFFFFF', max_length=18)),
                ('resistant_to', models.ManyToManyField(blank=True, related_name='resistant', to='pokedex.Type')),
                ('weak_to', models.ManyToManyField(blank=True, to='pokedex.Type')),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('pokedex_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.FilePathField(path='/mnt/d/workspace/projects/pokemon/pokedex/static/img')),
                ('poke_type', models.ManyToManyField(to='pokedex.Type')),
            ],
            options={
                'verbose_name_plural': 'Pokemon',
            },
        ),
    ]
