# Generated by Django 3.2 on 2021-06-24 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='resistant_to',
            field=models.ManyToManyField(blank=True, related_name='_pokedex_type_resistant_to_+', to='pokedex.Type'),
        ),
        migrations.AlterField(
            model_name='type',
            name='weak_to',
            field=models.ManyToManyField(blank=True, related_name='_pokedex_type_weak_to_+', to='pokedex.Type'),
        ),
    ]
