# Generated by Django 3.2 on 2021-06-25 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='immune_to',
            field=models.ManyToManyField(blank=True, related_name='immune', to='pokedex.Type'),
        ),
    ]
