INSERT INTO move (name, type) VALUES
  ('Flamethrower', 'FIRE'),
  ('Water Gun', 'WATER'),
  ('Razor Leaf', 'GRASS'),
  ('Move 4', 'FIRE'),
  ('Move 5', 'WATER'),
  ('Move 6', 'GRASS'),
  ('Move 7', 'FIRE'),
  ('Move 8', 'WATER'),
  ('Move 9', 'GRASS'),
  ('Move 10', 'FIRE'),
  ('Move 11', 'WATER'),
  ('Move 12', 'GRASS'),
  ('Move 13', 'FIRE'),
  ('Move 14', 'WATER'),
  ('Move 15', 'GRASS');

INSERT INTO pokemon (id, name, primary_type, secondary_type) VALUES
  (1, 'Bulbasaur', 'GRASS', NULL),
  (2, 'Ivysaur', 'GRASS', NULL),
  (3, 'Venusaur', 'GRASS', NULL),
  (4, 'Charmander', 'FIRE', NULL),
  (5, 'Charmeleon', 'FIRE', NULL),
  (6, 'Charizard', 'FIRE', NULL),
  (7, 'Squirtle', 'WATER', NULL),
  (8, 'Wartortle', 'WATER', NULL),
  (9, 'Blastoise', 'WATER', NULL),
  (10, 'Caterpie', 'BUG', NULL),
  (11, 'Metapod', 'BUG', NULL),
  (12, 'Butterfree', 'BUG', 'FLYING'),
  (13, 'Weedle', 'BUG', 'POISON'),
  (14, 'Kakuna', 'BUG', 'POISON'),
  (15, 'Beedrill', 'BUG', 'POISON');
